server:
  port: 20003
again:
  websocket:
    netty:
      leak_detector_level: DISABLED
      boss_group_thread_count: 1
      worker_group_thread_count: 12
      max_payload_size: 65536
      bind_port: 20004
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://192.168.1.242:3307/test?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
  application:
    name: again-web
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
  instance:
    prefer-ip-address: true #显示 ip
