spring:
  application:
    name: again-web
  profiles:
    active: dev
server:
  port: 20003
again:
  websocket:
    netty:
      leak_detector_level: DISABLED
      boss_group_thread_count: 1
      worker_group_thread_count: 12
      max_payload_size: 65536
      bind_port: 20004
  iplimit: # IP限流
    enable: true  # 开启
    timeout: 1000  # 每1秒内（单位毫秒）
    limit: 20 # 每个ip限制20个请求（单位个）
  ratelimit: # 全局限流
    enable: true  # 开启
    timeout: 1000 # 每1秒内（单位毫秒）
    limit: 200 # 总限制200个请求（单位个）
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
    fetch-registry: true
  instance:
    prefer-ip-address: true #显示 ip
file:
  storage:
    type: aliyun
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key: access-key
    access-secret: access-secret
    bucket-name: bucket-name
pulsar:
  service-url: pulsar://192.168.1.228:6650
feign:
  hystrix:
    enabled: true #开启 服务熔断
  client:
    config:
      default:
        retryer: feign.Retryer.Default #设置超时重试策略,防止首次启动超时
##### Ribbon 配置
ribbon:
  # 连接超时
  ConnectTimeout: 5000
  # 响应超时
  ReadTimeout: 5000
ignored:
  # 限流及黑名单不拦截的路径
  limitUrls:
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
