// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.again.cloud;

public interface RequestOrBuilder extends
		// @@protoc_insertion_point(interface_extends:Request)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>string request = 1;</code>
	 */
	java.lang.String getRequest();

	/**
	 * <code>string request = 1;</code>
	 */
	com.google.protobuf.ByteString getRequestBytes();

}
