// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.again.cloud;

/**
 * <pre>
 * 定义通用的 Grpc 响应体
 * </pre>
 *
 * Protobuf type {@code Response}
 */
public final class Response extends com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:Response)
		ResponseOrBuilder {

	private static final long serialVersionUID = 0L;

	// Use Response.newBuilder() to construct.
	private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
		super(builder);
	}

	private Response() {
		response_ = "";
	}

	@java.lang.Override
	public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
		return this.unknownFields;
	}

	private Response(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		this();
		if (extensionRegistry == null) {
			throw new java.lang.NullPointerException();
		}
		int mutable_bitField0_ = 0;
		com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
		try {
			boolean done = false;
			while (!done) {
				int tag = input.readTag();
				switch (tag) {
				case 0:
					done = true;
					break;
				case 10: {
					java.lang.String s = input.readStringRequireUtf8();

					response_ = s;
					break;
				}
				default: {
					if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
						done = true;
					}
					break;
				}
				}
			}
		}
		catch (com.google.protobuf.InvalidProtocolBufferException e) {
			throw e.setUnfinishedMessage(this);
		}
		catch (java.io.IOException e) {
			throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
		}
		finally {
			this.unknownFields = unknownFields.build();
			makeExtensionsImmutable();
		}
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return com.again.cloud.GrpcService.internal_static_Response_descriptor;
	}

	@java.lang.Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
		return com.again.cloud.GrpcService.internal_static_Response_fieldAccessorTable.ensureFieldAccessorsInitialized(
				com.again.cloud.Response.class, com.again.cloud.Response.Builder.class);
	}

	public static final int RESPONSE_FIELD_NUMBER = 1;

	private volatile java.lang.Object response_;

	/**
	 * <code>string response = 1;</code>
	 */
	public java.lang.String getResponse() {
		java.lang.Object ref = response_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		}
		else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			response_ = s;
			return s;
		}
	}

	/**
	 * <code>string response = 1;</code>
	 */
	public com.google.protobuf.ByteString getResponseBytes() {
		java.lang.Object ref = response_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			response_ = b;
			return b;
		}
		else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	private byte memoizedIsInitialized = -1;

	@java.lang.Override
	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1)
			return true;
		if (isInitialized == 0)
			return false;

		memoizedIsInitialized = 1;
		return true;
	}

	@java.lang.Override
	public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
		if (!getResponseBytes().isEmpty()) {
			com.google.protobuf.GeneratedMessageV3.writeString(output, 1, response_);
		}
		unknownFields.writeTo(output);
	}

	@java.lang.Override
	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1)
			return size;

		size = 0;
		if (!getResponseBytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, response_);
		}
		size += unknownFields.getSerializedSize();
		memoizedSize = size;
		return size;
	}

	@java.lang.Override
	public boolean equals(final java.lang.Object obj) {
		if (obj == this) {
			return true;
		}
		if (!(obj instanceof com.again.cloud.Response)) {
			return super.equals(obj);
		}
		com.again.cloud.Response other = (com.again.cloud.Response) obj;

		boolean result = true;
		result = result && getResponse().equals(other.getResponse());
		result = result && unknownFields.equals(other.unknownFields);
		return result;
	}

	@java.lang.Override
	public int hashCode() {
		if (memoizedHashCode != 0) {
			return memoizedHashCode;
		}
		int hash = 41;
		hash = (19 * hash) + getDescriptor().hashCode();
		hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
		hash = (53 * hash) + getResponse().hashCode();
		hash = (29 * hash) + unknownFields.hashCode();
		memoizedHashCode = hash;
		return hash;
	}

	public static com.again.cloud.Response parseFrom(java.nio.ByteBuffer data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.again.cloud.Response parseFrom(java.nio.ByteBuffer data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.again.cloud.Response parseFrom(com.google.protobuf.ByteString data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.again.cloud.Response parseFrom(com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.again.cloud.Response parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.again.cloud.Response parseFrom(byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.again.cloud.Response parseFrom(java.io.InputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static com.again.cloud.Response parseFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	public static com.again.cloud.Response parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
	}

	public static com.again.cloud.Response parseDelimitedFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
	}

	public static com.again.cloud.Response parseFrom(com.google.protobuf.CodedInputStream input)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static com.again.cloud.Response parseFrom(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	@java.lang.Override
	public Builder newBuilderForType() {
		return newBuilder();
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(com.again.cloud.Response prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}

	@java.lang.Override
	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}

	/**
	 * <pre>
	 * 定义通用的 Grpc 响应体
	 * </pre>
	 *
	 * Protobuf type {@code Response}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:Response)
			com.again.cloud.ResponseOrBuilder {

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.again.cloud.GrpcService.internal_static_Response_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.again.cloud.GrpcService.internal_static_Response_fieldAccessorTable
					.ensureFieldAccessorsInitialized(com.again.cloud.Response.class,
							com.again.cloud.Response.Builder.class);
		}

		// Construct using com.again.cloud.Response.newBuilder()
		private Builder() {
			maybeForceBuilderInitialization();
		}

		private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			super(parent);
			maybeForceBuilderInitialization();
		}

		private void maybeForceBuilderInitialization() {
			if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
			}
		}

		@java.lang.Override
		public Builder clear() {
			super.clear();
			response_ = "";

			return this;
		}

		@java.lang.Override
		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return com.again.cloud.GrpcService.internal_static_Response_descriptor;
		}

		@java.lang.Override
		public com.again.cloud.Response getDefaultInstanceForType() {
			return com.again.cloud.Response.getDefaultInstance();
		}

		@java.lang.Override
		public com.again.cloud.Response build() {
			com.again.cloud.Response result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		@java.lang.Override
		public com.again.cloud.Response buildPartial() {
			com.again.cloud.Response result = new com.again.cloud.Response(this);
			result.response_ = response_;
			onBuilt();
			return result;
		}

		@java.lang.Override
		public Builder clone() {
			return (Builder) super.clone();
		}

		@java.lang.Override
		public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return (Builder) super.setField(field, value);
		}

		@java.lang.Override
		public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
			return (Builder) super.clearField(field);
		}

		@java.lang.Override
		public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
			return (Builder) super.clearOneof(oneof);
		}

		@java.lang.Override
		public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
				java.lang.Object value) {
			return (Builder) super.setRepeatedField(field, index, value);
		}

		@java.lang.Override
		public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return (Builder) super.addRepeatedField(field, value);
		}

		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.Message other) {
			if (other instanceof com.again.cloud.Response) {
				return mergeFrom((com.again.cloud.Response) other);
			}
			else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(com.again.cloud.Response other) {
			if (other == com.again.cloud.Response.getDefaultInstance())
				return this;
			if (!other.getResponse().isEmpty()) {
				response_ = other.response_;
				onChanged();
			}
			this.mergeUnknownFields(other.unknownFields);
			onChanged();
			return this;
		}

		@java.lang.Override
		public final boolean isInitialized() {
			return true;
		}

		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			com.again.cloud.Response parsedMessage = null;
			try {
				parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				parsedMessage = (com.again.cloud.Response) e.getUnfinishedMessage();
				throw e.unwrapIOException();
			}
			finally {
				if (parsedMessage != null) {
					mergeFrom(parsedMessage);
				}
			}
			return this;
		}

		private java.lang.Object response_ = "";

		/**
		 * <code>string response = 1;</code>
		 */
		public java.lang.String getResponse() {
			java.lang.Object ref = response_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				response_ = s;
				return s;
			}
			else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>string response = 1;</code>
		 */
		public com.google.protobuf.ByteString getResponseBytes() {
			java.lang.Object ref = response_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				response_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>string response = 1;</code>
		 */
		public Builder setResponse(java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}

			response_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>string response = 1;</code>
		 */
		public Builder clearResponse() {

			response_ = getDefaultInstance().getResponse();
			onChanged();
			return this;
		}

		/**
		 * <code>string response = 1;</code>
		 */
		public Builder setResponseBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			response_ = value;
			onChanged();
			return this;
		}

		@java.lang.Override
		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.setUnknownFieldsProto3(unknownFields);
		}

		@java.lang.Override
		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.mergeUnknownFields(unknownFields);
		}

		// @@protoc_insertion_point(builder_scope:Response)

	}

	// @@protoc_insertion_point(class_scope:Response)
	private static final com.again.cloud.Response DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new com.again.cloud.Response();
	}

	public static com.again.cloud.Response getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<Response> PARSER = new com.google.protobuf.AbstractParser<Response>() {
		@java.lang.Override
		public Response parsePartialFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return new Response(input, extensionRegistry);
		}
	};

	public static com.google.protobuf.Parser<Response> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<Response> getParserForType() {
		return PARSER;
	}

	@java.lang.Override
	public com.again.cloud.Response getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
