// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.again.cloud;

public interface ResponseOrBuilder extends
		// @@protoc_insertion_point(interface_extends:Response)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>string response = 1;</code>
	 */
	java.lang.String getResponse();

	/**
	 * <code>string response = 1;</code>
	 */
	com.google.protobuf.ByteString getResponseBytes();

}
