server:
  port: 30000
spring:
  application:
    name: again-search
eureka:
  instance:
    prefer-ip-address: true #当我们在eureka中点击服务的地址的时候打开的是以ip开头的
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
again:
  starter:
    es:
      host: scrm-bus-es
      port: 9100
      port1: 9101
      port2: 9102
      tcp_port: 9400
      tcp_port1: 9500
      tcp_port2: 9600
      index: wscrm_message
      type: message
      cluster_name: scrm-es
      user_name:
      password: