server:
  port: 20001
spring:
  application:
    name: again-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/mrluoyingjie/mrjackie-luo #配置git的地址
          search-paths:
            - openplatform-cache
eureka:
  instance:
    prefer-ip-address: true #当我们在eureka中点击服务的地址的时候打开的是以ip开头的
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka

